name: Deploy Staging 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    name: Deploy to staging server
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Execute deployment command
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_STG_PORT: ${{ secrets.APP_STG_PORT }}
          MINIO_STG_ENDPOINT: ${{ secrets.MINIO_STG_ENDPOINT }}
          MINIO_STG_ACCESS_KEY: ${{ secrets.MINIO_STG_ACCESS_KEY }}
          MINIO_STG_SECRET_KEY: ${{ secrets.MINIO_STG_SECRET_KEY }}
          GIT_URL: ${{ secrets.GIT_URL }}
          APP_STG_PATH: ${{ vars.APP_STG_PATH }}
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          envs: APP_STG_PORT, MINIO_STG_ENDPOINT, MINIO_STG_ACCESS_KEY, MINIO_STG_SECRET_KEY, GIT_URL, APP_STG_PATH
          script: |

            if [[ -d "$APP_STG_PATH" ]]; then
              cd $APP_STG_PATH
              sudo docker compose down
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL $APP_STG_PATH
              cd $APP_STG_PATH
            fi

            #kalo ada udpate env
            echo "APP_STG_PORT=$APP_STG_PORT" > .env
            echo "MINIO_STG_ENDPOINT=$MINIO_STG_ENDPOINT" >> .env
            echo "MINIO_STG_ACCESS_KEY=$MINIO_STG_ACCESS_KEY" >> .env
            echo "MINIO_STG_SECRET_KEY=$MINIO_STG_SECRET_KEY" >> .env

            #running app
            sudo docker compose up --build --detach pacmusic-stg
                    
      - name: Hit Endpoint
        run:  |
          sleep 20
          curl ${{ secrets.STG_URL }}
